### PR TITLE
Update the README's installation steps for `dagger.android`

### PR DESCRIPTION
**Pull request by oldergod**

### CODE REVIEW

**Comment by gk5885** [comment]
These are all `@Beta` APIs.  I would not recommend adding them to the readme in this way quite yet as it implies more stability than they currently have.

**Comment by oldergod** [comment]
I agree. At the moment, there being `@Beta` APIs can only be found by checking the `dagger.android` source. It would probably be good to say so as well in the Android documentation. I'll change both then.

**Comment by oldergod** [comment]
I updated the README as well. I will let you guys decide if you want to add it both in the docs and the readme then.
Let me know if there is anything missing.

**Comment by ronshapiro** [comment]
We pulled this in (in a slightly different form) since we've been getting a ton of questions about this.

**Comment by oldergod** [comment]
thank you !

**Pull request closed without merging**
