### PR TITLE
Fix activity-graphs sample compilation error

### PR DESCRIPTION
**Pull request by nguyentruongtho**
Just want to give a hand :dancer: regarding this https://github.com/google/dagger/issues/87

### CODE REVIEW

**Comment by cgruber** [comment]
Thanks for doing this.  We definitely were focused on a lot of edge-case behavior internally.  But this is super-helpful.  Reviewing.

**Comment by cgruber** [comment]
This looks good.  It still doesn't reflect some of the practices we're seeing evolve, so we'll need to review them more thoroughly later - but as simple examples of ways you _can_ use Dagger 2 on android, this fix makes them work.  So... LGTM.

**Comment by cgruber** [comment]
If you're willing, can you please rebase against master?

**Comment by nguyentruongtho** [comment]
Hmm, as far as I checked, this sample simply aims to demonstrate how to create Activity scope with Dagger2. https://github.com/google/dagger/blob/master/examples/android-activity-graphs/README.md

`If you're willing, can you please rebase against master?`

Sure, just in few minutes.

**Comment by nguyentruongtho** [comment]
Am I the only one who hate travis -_-.

**Comment by cgruber** [comment]
Man.  What the hell is going on on Travis?  I've re-started the job a couple of times.  Do you want to maybe rebase -i and force a new commit ref no, and push -f to force travis to try again?  I don't know if it's this branch or environmental...

**Comment by nguyentruongtho** [comment]
Problem turns out to be the compatibility issue between Maven 3.2.5 (on Travis) and android-maven-plugin. I will push a fix for it very soon.

**Comment by cgruber** [comment]
Ok - this looks good.  I'll merge in.

**Pull request merged**
