### PR TITLE
Fix README license based on http://google.github.io/dagger/users-guide

### PR DESCRIPTION
**Pull request by shiraji**

### CODE REVIEW

**Comment by gk5885** [comment]
Hey, @cgruber, do you know if this is correct?

**Comment by ronshapiro** [comment]
I think we want this as "The Dagger Authors"

**Comment by shiraji** [comment]
Like this?

```
    Copyright 2016 The Dagger Authors
    Copyright 2012 Square, Inc.
```

**Comment by ronshapiro** [comment]
`Copyright 2012 The Dagger Authors`

**Comment by ronshapiro** [comment]
Great - I'm pulling this in, and also updating the users-guide (you initially updated the README). Thanks for the contribution!

**Comment by shiraji** [comment]
Resolved conflict. Thanks for considering this PR!

**Comment by ronshapiro** [comment]
All merged - thank you!

**Pull request closed without merging**
