### PR TITLE
Add @SuppressWarnings("uncheced") for every generate component

### PR DESCRIPTION
**Pull request by talentprince**
Add @SuppressWarnings("uncheced") for every generate component

### CODE REVIEW

**Comment by tbroyer** [comment]
Any reason you don't simply update the PR rather than closing/reopening? It generates mail noise for those if us subscribed to the project.

**Comment by talentprince** [comment]
sorry, I just dont know that...

**Comment by tbroyer** [comment]
> Pull requests can be sent from any branch or commit but it's recommended that a topic branch be used so that follow-up commits can be pushed to update the pull request if necessary.

— Source: https://help.github.com/articles/using-pull-requests/

Pushing to your branch will automatically update the PR with new commits (and also works with `push --force`).
I'd recommend (for next time) to not use `master` as your source branch though (create one branch per topic)

**Comment by talentprince** [comment]
ha that make sense. thanks for knowledge

发自我的 iPhone

**Pull request closed without merging**
