### PR TITLE
Merge out new changes from google's internal repository

### PR DESCRIPTION
**Pull request by cgruber**
A variety of changes:

  * Various Fixes 
    - naming collision edge-cases
    - package visibility issues with `*_MonitoringModules`
    - test to ensure javapoet handles #279 gracefully.
    - `@CheckReturnValue` added to some methods (use github.com/google/error-prone to get the benefits of this)
    - fix to map-bound producers. 
  * Documentation improvements
  * Automated cleanups
  * Added `@ProductionScope` to limit bindings to the production component or subcomponent where they're included.
  * Some optimizations for less code generation
  * Gws support from pull request #119
  * Lock down static-provides-method-only modules with a static constructor

### CODE REVIEW

**Comment by cgruber** [comment]
@jnehlmeier - can you please comment on this thread that you consent to having your changes merged?

**Comment by jnehlmeier** [comment]
I consent that my changes are being contributed to Google and can be merged.

**Comment by cgruber** [comment]
Thanks.  CLA-bot weirdness, so thanks for the explicit mention.  It's clear you signed, just wanted that extra bit.

**Comment by ronshapiro** [comment]
LGTM

**Pull request merged**
