### PR TITLE
fix links to JavaDoc in index.md

### LINKED ISSUE #164: Documentation links don't work
When i try to see documentation for different links:
- http://google.github.io/api/latest/dagger/Component.html;
- http://google.github.io/api/latest/dagger/Component.html#modules();
- http://google.github.io/api/latest/dagger/Subcomponent.html;
- http://google.github.io/api/latest/dagger/Component.html#component-relationships;

Server returns 404 error.

May be others links have the same issue.

### PR DESCRIPTION
**Pull request by nanaze**
fixed #164

### CODE REVIEW

**Comment by tbroyer** [comment]
I'm pretty sure only your component link is OK; others are missing the package.

Also, was there any problem with #174 ?

**Comment by nanaze** [comment]
whoops, fixed the others.

Dunno which they'd prefer. I am a Google employee, but do not work on Dagger. I'm going to ping them to get one of these merged.

**Comment by nanaze** [comment]
I'm going to drop this in favor of the relative links, which are probably preferable.

I'll ping the dagger team to merge.

**Comment by tbroyer** [comment]
> I am a Google employee

Ah, I knew I had already seen that name ;-)

**Pull request closed without merging**
