### PR TITLE
Fix eclipse JDT compilation failing when moduleElement is initially u…

### PR DESCRIPTION
**Pull request by facboy**
…navailable (eg because it is also generated by annotation processsing).

### CODE REVIEW

**Comment by facboy** [comment]
not sure if this fixes other issues in #912.

**Comment by facboy** [comment]
Is there any feedback on this?

**Comment by facboy** [comment]
@ronshapiro can we get this merged?

**Comment by facboy** [comment]
Fixes #1114.

**Comment by ronshapiro** [comment]
This should be covered in `BasicAnnotationProcessor`, which `ComponentProcessor` extends. 

Can you provide a sample program that fails with jdt (and ideally something that we can see if it also fails with `javac`)?

**Comment by facboy** [comment]
The project that causes it is proprietary, I'll need a bit of time to come up with a sample project.  FYI it does not occur with `javac` (or in Intellij).  Pesky Eclipse users! :)

**Comment by facboy** [comment]
Added sample project and stacktrace to #1114.

**Comment by facboy** [comment]
This is probably not necessary any more.

**Pull request closed without merging**
