### PR TITLE
Added install info to README for Gradle users.

### PR DESCRIPTION
**Pull request by kkovach**

### CODE REVIEW

**Comment by ronshapiro** [comment]
@kkovach this is great, can you rebase so we can pull this in?

**Comment by kkovach** [comment]
Done.

**Comment by oreissig** [comment]
I'd love to see this change merged, too. What's the state?

**Comment by friederbluemle** [comment]
@kkovach Can you rebase your commit (to remove the empty merge commits)?

**Comment by ronshapiro** [comment]
I'd really like to get this in - a bug in MOE is holding us back, but I hope to have a workaround for it soon so that we can merge this in. Thanks for your patience!

**Pull request closed without merging**
