### PR TITLE
Moe writing branch from 9f986abd0f985e717dde1476aeaf058df50064ff

### PR DESCRIPTION
**Pull request by cgruber**
A variety of changes, notably:

  * Explicit component builder support (Slated for 2.1)
  * Some increased testing coverage
  * A few improved validations

### CODE REVIEW

**Comment by cgruber** [comment]
Ping to @gk5885.

**Comment by cgruber** [comment]
Ah crap - i have to re-base.  Sorry - I'll re-ping when I fix it.

**Comment by gk5885** [comment]
LGTM

**Comment by cgruber** [comment]
Jeez.  one of the travis builds (oraclejdk) hasn't even started yet.  :/  I'll wait.

**Pull request merged**
