### PR TITLE
Release 2.0.2

### PR DESCRIPTION
**Pull request by cgruber**
A patch release, most crucially inlcuding:
  * A fix to the way processor validation of types is done that permits dagger to play more nicely with other processors, avoiding over-validating aspects that it doesn't need, which may yet not have been generated by other processors in a different round of processing.
  * Some improved error reporting for edge-cases
  * Fix to prevent incompatible versions of Guava on the classpath from blowing up processing
  * Support a more robust set of types for map keys in map bindings (primitive types, etc.)

### CODE REVIEW

**Comment by cgruber** [comment]
Note - tatjana was a googler at the time of the CLA-offending commit above.

**Comment by cgruber** [comment]
I give up fighting CLAbot.

**Comment by gk5885** [comment]
LGTM

**Comment by cgruber** [comment]
Released. Closing this pull request.

**Pull request closed without merging**
