### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by oreissig**
I updated external libraries to their newest version. No major version jump occured and no changes to the code or tests were necessary.

### CODE REVIEW

**Comment by oreissig** [comment]
I just signed the CLA.

**Comment by ronshapiro** [comment]
There's a change internally that should be synced early this week which
does this, with the exception of a couple upgrades that we aren't able to
support internally yet (like Mockito).

**Comment by oreissig** [comment]
What's the problem with mockito? Semantically there are no breaking changes, and it is only used as test dependency anyway, so there should be no problems for other modules.

**Comment by ronshapiro** [comment]
There isnt any problem in particular, but internally we only support having
one version of a library across all of Google. So if we upgrade mockito
externally but not internally we could have an inconsistency.

**Comment by oreissig** [comment]
Oh, what a bummer.

Guess the PR can be closed when you cannot choose library versions freely anyway?

**Pull request closed without merging**
