### PR TITLE
Set util scripts non-executable

### PR DESCRIPTION
**Pull request by cgruber**
Set util/*.sh scripts non-executable and explicitly execute their shell commands in travis configuration.  This prevents constant thrash of executable bits between google's internal repo and github because: moe

Note: this is what we do on google/truth.

### CODE REVIEW

**Comment by sameb** [comment]
I fixed this in guice by setting a bit in the moe config.  checkout guice's moe config internally for the bits.

**Comment by cgruber** [comment]
Yeah?  I'll peek at it. Thanks @sameb.

**Comment by cgruber** [comment]
Found it.  Thanks.

**Comment by cgruber** [comment]
Heh.  And someone fixed the truth moe config while I wasn't looking.  Solving an old problem. I'll patch up our other projects.

**Pull request closed without merging**
