### PR TITLE
Fix broken documentation links in migration guide

### PR DESCRIPTION
**Pull request by ronshapiro**

### CODE REVIEW

**Comment by ronshapiro** [comment]
I signed it!

**Comment by IRus** [comment]
@googlebot Please merge this minor fix

**Comment by vovkab** [comment]
Rebase?

**Comment by ronshapiro** [comment]
Submitted internally first here: 7f15690bfd2bfa090d2e93c10a0f8d81b3533582. This is now synced with the public docs.

**Pull request closed without merging**
