### PR TITLE
Upgrade Kotlin and KSP to latest stable versions

### PR DESCRIPTION
**Pull request by kaeawc**
I've built Dagger with these versions and validated a KSP classloader leak fix. Dagger consumers would benefit from this, so I'm attempting to help upgrade Dagger.

### CODE REVIEW

**Comment by bcorso** [comment]
@kaeawc you should be free to choose the kotlin/ksp versions in your own project independently of which versions Dagger uses to build its own code. In particular, I wouldn't expect these changes to affect downstream Dagger users.

Can you try updating Kotlin/KSP in your own codebase and verify if you get the fixes without this change?

**Comment by kaeawc** [comment]
@bcorso I didn't realize when I wrote this change that it was a compile only dependency and have since verified the fix without a need from Dagger to update. Probably the only thing the community would be interested in is a release with updated kotlin metadata. If this PR doesn't help with that we can just close it.

**Comment by bcorso** [comment]
@kaeawc thanks for confirming.

> Probably the only thing the community would be interested in is a release with updated kotlin metadata. 

Just to clarify, are you asking for a release with the Dagger's current kotlin-metadata (`v2.0.0-Beta5`) or something newer? Asking because I think there are API changes with `v2.0.0+` that we haven't resolved yet.

**Comment by kaeawc** [comment]
Something newer, so I'll just wait until those are resolved. Are there open issues for those?

**Comment by bcorso** [comment]
> Are there open issues for those?

Not yet. Feel free to create an issue for it though.

**Pull request closed without merging**
