### PR TITLE
Upgrade build tool version to 26.0.1

### PR DESCRIPTION
**Pull request by hansonchar**
Currently the build tool version specified in WORKSPACE is:

- api_level = 25,
- build_tools_version = "25.0.2"

To build all targets via 

  `bazel build ...`

would fail with:

>ERROR: /Users/hchar/github/dagger/javatests/dagger/android/support/functional/BUILD:20:1: no such package '@androidsdk//com.android.support': Bazel requires Android build tools version 26.0.1 or newer, 25.0.2 was provided and referenced by '//javatests/dagger/android/support/functional:functional'.
>ERROR: /Users/hchar/github/dagger/javatests/dagger/android/support/functional/BUILD:20:1: no such package '@androidsdk//com.android.support': Bazel requires Android build tools version 26.0.1 or newer, 25.0.2 was provided and referenced by '//javatests/dagger/android/support/functional:functional'.
>ERROR: Analysis of target '//javatests/dagger/android/support/functional:functional' failed; build aborted.

Upgrading to:

+    api_level = 26,
+    build_tools_version = "26.0.1"

fixes the problem.

### CODE REVIEW

**Comment by hansonchar** [comment]
For the continuous integration to succeed, it seems the latest Android SDK Manager (api level 26) would need to be installed on your system that runs the continuous integration.

**Comment by JakeWharton** [comment]
You need to update the .travis.yml file as well.

I'm surprised this broke as only Bazel 0.5.4 requires build tools 26.0.1. I guess we're not pinned to a specific version?

**Comment by JakeWharton** [comment]
Oh or are you building locally with 0.5.4?

**Comment by hansonchar** [comment]
$ bazel version
Build label: 0.5.4-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 25 16:55:29 2017 (1503680129)
Build timestamp: 1503680129
Build timestamp as int: 1503680129

**Comment by hansonchar** [comment]
Yeah, build success!

**Comment by ronshapiro** [comment]
Sorry I wasn't on top of this when you sent it. I'm going to close it now since it's out of date.

**Pull request closed without merging**
