### PR TITLE
remove unused maven config

### PR DESCRIPTION
**Pull request by gengjiawen**

### CODE REVIEW

**Comment by ronshapiro** [comment]
Merged in https://github.com/google/dagger/commit/92cbe34306f061e79b94cc4aa84d6c90fb6ebff8 but I didn't like properly

**Comment by gengjiawen** [comment]
> but I didn't like properly

What do you mean by this ?

**Comment by ronshapiro** [comment]
*didn't properly link to this PR in the commit message. 

We merged this internally and then synced it out in 92cbe34 (still authored by you). That commit message should have had "Closes https://github.com/google/dagger/pull/820" but my line had appended "/files" at the end. 

This is all details though - the contents of this PR are merged into master. Thanks for your contribution!

**Comment by gengjiawen** [comment]
: )

**Pull request closed without merging**
