### PR TITLE
Replaced 'compile' with 'implementation'

### PR DESCRIPTION
**Pull request by weeeBox**
'compile' is now deprecated and generates Android Studio build time warnings

### CODE REVIEW

**Comment by JakeWharton** [comment]
Dupe of #1329, #1324, and #1190 (see also #1191 and #914)

**Comment by weeeBox** [comment]
@JakeWharton, why won't you merge one of them? Adding Kotlin instructions with `kapt` won't hurt as well.

**Comment by JakeWharton** [comment]
Not my project.

**Comment by weeeBox** [comment]
@JakeWharton, is there a way to get those changes merged?

**Comment by bcorso** [comment]
There's a long discussion on #1130. Let's continue any discussion there.

**Pull request closed without merging**
