### PR TITLE
support androidx

### PR DESCRIPTION
**Pull request by Tangpj**
support androidx

### CODE REVIEW

**Comment by Tangpj** [comment]
I signed it!

**Comment by JakeWharton** [comment]
I don't think a monolothic library for AndroidX is a good idea. Ideally we would separate the functionally by associated library.

**Comment by Tangpj** [comment]
Ok. So in actual development, you are not using AndroidX?
How are you going to provide support for AndroidX?

**Comment by ronshapiro** [comment]
Thanks for the contribution!

Like @JakeWharton, I think the right thing to do is have `dagger.android.fragment` (or `dagger.androidx.fragment`, not sure) packages for each separate `androidx` package. 

At the moment, I think Jetifier+`dagger.android.support` is the right way to go about this (especially once Jetifier stops pushing people to `dagger-2.16`, which should be soon). We have some things in the works now to make supporting the other packages easier, and once that's finished we can think more about expanding `androidx` support.

**Comment by Tangpj** [comment]
Ok, thank you for your answer. @JakeWharton @ronshapiro

**Pull request closed without merging**
