### PR TITLE
Merge from moe writing branch from 9f986abd0f985e717dde1476aeaf058df50064ff

### PR DESCRIPTION
**Pull request by cgruber**
A variety of changes imported from google's internal repository, including:

  * Generated sources are now formatted in google style using [google-java-format](http://github.com/google/google-java-format)
  * Some initial work for full compatibility with the JSR-330 spec and TCK
    - Cyclic dependencies are now supported if they are broken by an indirection of injecting a `Lazy<T>` or `Provider<T>` (helping bring Dagger into compliance with JSR-330, and addressing #200)
    - Initially posted the JSR-330 TCK sources to show how dagger is complying, but reverted, as we will be relying on the published binary artifact of the TCK.
    - Other compliance work is still in google's internal repository, but is delayed pending a push of [compile-testing](http://github.com/google/compile-testing)
 * Some build-time optimizations, reducing the time to produce very large graphs, or graphs with large numbers of modules
 * Some correctness fixes to set bindings in subcomponents.
 * Some improved error reporting on missing bindings in the context of subcomponents
 * Some fixes to javadocs, particularly around `Lazy<T>`
 * Type inference fixes that should make Dagger less brittle building in Javac 8/9+ and more generally deal with type inference incompatibilities between versions of javac. 
 * Miscellaneous build changes to accommodate the above
 * Miscellaneous re-factorings in support of the above or forthcoming features, and to move some code into [auto-common](http://github.com/google/auto)
 * And more!

### CODE REVIEW

**Comment by cgruber** [comment]
clabot lies.  these are googler originated changes.

**Comment by cgruber** [comment]
Ok, this is hella-weird.  It's succeeding on oracle JDK but on OpenJDK one test is failing, when tested from the pull request branch, but both pass when tested from the branch push.  I don't know if this test is flaky, or what, but it's kind of a problem, since if it fails on the merge, we won't get a snapshot. 

@netdpb and @gk5885 - can you folks look at this build output and think through whether this is just a flaky test, or some environemental issue. 

https://travis-ci.org/google/dagger/builds/77860604

**Comment by netdpb** [comment]
It's weird. The two MembersInjector fields are unused in the subcomponent,
and they appear out of order.

   1. Why are they even there, if they're unused?
   2. Why are they out of order? Are we using HashSet or HashMap instead of
   a data structure with predictable iteration order?


On Sat, Aug 29, 2015 at 6:23 PM Christian Edward Gruber <
notifications@github.com> wrote:

> Ok, this is hella-weird. It's succeeding on oracle JDK but on OpenJDK one
> test is failing, when tested from the pull request branch, but both pass
> when tested from the branch push. I don't know if this test is flaky, or
> what, but it's kind of a problem, since if it fails on the merge, we won't
> get a snapshot.
>
> @netdpb <https://github.com/netdpb> and @gk5885
> <https://github.com/gk5885> - can you folks look at this build output and
> think through whether this is just a flaky test, or some environemental
> issue.
>
> https://travis-ci.org/google/dagger/builds/77860604
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/dagger/pull/229#issuecomment-136057467>.
>
-- 
--dpb

**Comment by cgruber** [comment]
Ron has a fix for the dagger example projects going unbuildable, which I'm incorporating.

**Comment by cgruber** [comment]
Huzzah!  Builds clean!

**Comment by gk5885** [comment]
Lgtm

**Comment by cgruber** [comment]
After a long journey, this branch cometh home.  (For the record, I got an LGTM from @gk5885 outside of this issue).

**Comment by cgruber** [comment]
Oh, and hten also in this issue, but github lags. :)

**Pull request merged**
