### PR TITLE
MOE sync for 2.4 release

### LINKED ISSUE #356: Dagger 2.2 to 2.3 (or 2.4)
I have updated my Dagger version from 2.2 to 2.3 and now facing following problem:

`Error:Execution failed for task ':app:compileDebugJavaWithJavac'.`
`java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSetMultimap$Builder.putAll(Ljava/lang/Iterable;)Lcom/google/common/collect/ImmutableSetMultimap$Builder;`

### PR DESCRIPTION
**Pull request by ronshapiro**
- Adds `@Binds` API for delegating one binding to another
- Adds `@IntoSet`, `@ElementsIntoSet` and `@IntoMap` to replace `@Provides(type = ...)` and `@Produces(type = ...)`
- Allow injection of `Provider<Lazy<Foo>>`
- Report an error if a `@Scope` annotation is applied to an `@Inject` constructor
- Remove the ability to set the production executor on a component builder.
- Ensure that no binding methods are binding framework types. 
- Update to JavaPoet 1.6.1
- New format of dependency traces in error messages
- Fixed bug: Exception when a binding in a parent that is used only in a subcomponent depends on a binding in the subcomponent

### CODE REVIEW

**Comment by JakeWharton** [comment]
No deprecation on `type=`?

**Comment by tbroyer** [comment]
While referenced in the PR comment/description, I don't see the commit about the google-java-format upgrade.

**Comment by ronshapiro** [comment]
@JakeWharton deprecation is coming, just finishing migrating internally. Definitely on the radar.
@tbroyer good catch - I saw the request internally but it hasn't been submitted yet. I'll make sure that gets in and do another sync before we release 2.4. Updating the description.

**Comment by gk5885** [comment]
LGTM

**Pull request merged**
