### PR TITLE
Update changelog with dagger 2 information, and reformat.

### PR DESCRIPTION
**Pull request by cgruber**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Ping. Changelog is really important part of the library! 2.0.2 was released, and the only way to see what was changed — go through all commits…

**Comment by chrisjenx** [comment]
Bump. This is what I was trying to highlight @gk5885 everyone outside of google/square has limited knowledge of whats "going on".

**Comment by viniciussoares** [comment]
+1 :thumbsup:

**Comment by cgruber** [comment]
I'm going to merge this internally.  I'll close this once we have synced out dagger, which should be in the next day or two.

**Comment by ronshapiro** [comment]
@cgruber looks like this was already done - ping me if I closed something abruptly.

**Pull request closed without merging**
